vich_uploader:
    db_driver: orm
    
    mappings:
        
        colis_uploads:
            uri_prefix: '/uploads/colis'
            upload_destination: '%kernel.project_dir%/public/uploads/colis'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false
            # specify the name of the field that will store the uploaded file
            # and the name of the property that holds the name of the file
            # in this case, the field is named "imageFile" and the property is "imageName"
            # make sure these names match the names you have used in your entity
        
            